/**
 * AUTOGENERATED by scripts/check-locales.ts — do not edit by hand.
 *
 * This file derives a `TranslationKey` string-literal union from `en.json`
 * and augments i18next's `CustomTypeOptions` so `t(key)` call sites get
 * autocomplete and compile-time checking against the source-of-truth catalog.
 *
 * Re-run `npm run check:locales` to regenerate after adding or removing keys.
 */

import 'i18next';
import type enCatalog from './en.json';

export type TranslationKey = keyof typeof enCatalog;

declare module 'i18next' {
  interface CustomTypeOptions {
    defaultNS: 'translation';
    returnNull: false;
    resources: {
      translation: typeof enCatalog;
    };
  }
}
