/**
 * Locale catalog parity and sort-order check.
 *
 * Validates that `frontend/src/locales/en.json` and `frontend/src/locales/pt-BR.json`:
 *   1. Have identical key sets (symmetric difference is empty).
 *   2. Every value is a non-empty string.
 *   3. Each file is sorted alphabetically by key.
 *
 * On success, emits `frontend/src/locales/keys.d.ts` containing:
 *   - `export type TranslationKey = keyof typeof enCatalog;`
 *   - A `declare module 'i18next'` block augmenting `CustomTypeOptions.resources`
 *     with `{ translation: typeof enCatalog }`, `defaultNS: 'translation'`,
 *     `returnNull: false`.
 *
 * Uses Node stdlib only — no new runtime dependencies.
 *
 * Exit code 0 on success, 1 on any failure (with a diagnostic printed to stderr).
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const REPO_ROOT = resolve(__dirname, '..');
const LOCALES_DIR = resolve(REPO_ROOT, 'frontend/src/locales');
const EN_PATH = resolve(LOCALES_DIR, 'en.json');
const PTBR_PATH = resolve(LOCALES_DIR, 'pt-BR.json');
const KEYS_DTS_PATH = resolve(LOCALES_DIR, 'keys.d.ts');

type Catalog = Record<string, unknown>;

function fail(message: string): never {
  process.stderr.write(`[check-locales] ERROR: ${message}\n`);
  process.exit(1);
}

function readCatalog(path: string): { raw: string; data: Catalog } {
  let raw: string;
  try {
    raw = readFileSync(path, 'utf8');
  } catch (err) {
    fail(`cannot read ${path}: ${(err as Error).message}`);
  }
  let data: unknown;
  try {
    data = JSON.parse(raw);
  } catch (err) {
    fail(`${path} is not valid JSON: ${(err as Error).message}`);
  }
  if (typeof data !== 'object' || data === null || Array.isArray(data)) {
    fail(`${path} must be a JSON object at the root`);
  }
  return { raw, data: data as Catalog };
}

function validateValues(path: string, data: Catalog): void {
  for (const [key, value] of Object.entries(data)) {
    if (typeof value !== 'string') {
      fail(`${path}: key "${key}" has non-string value (${typeof value})`);
    }
    if (value.length === 0) {
      fail(`${path}: key "${key}" has an empty string value`);
    }
  }
}

function validateSorted(path: string, data: Catalog): void {
  const keys = Object.keys(data);
  const sorted = [...keys].sort();
  for (let i = 0; i < keys.length; i++) {
    if (keys[i] !== sorted[i]) {
      fail(
        `${path} is not sorted alphabetically by key. ` +
          `First out-of-order key: "${keys[i]}" (expected "${sorted[i]}").`,
      );
    }
  }
}

function validateParity(enKeys: Set<string>, ptBrKeys: Set<string>): void {
  const onlyEn: string[] = [];
  const onlyPtBr: string[] = [];
  for (const k of enKeys) if (!ptBrKeys.has(k)) onlyEn.push(k);
  for (const k of ptBrKeys) if (!enKeys.has(k)) onlyPtBr.push(k);

  if (onlyEn.length === 0 && onlyPtBr.length === 0) return;

  const lines: string[] = ['catalog key sets diverge'];
  if (onlyEn.length > 0) {
    lines.push(`  keys in en.json but NOT in pt-BR.json (${onlyEn.length}):`);
    for (const k of onlyEn) lines.push(`    - ${k}`);
  }
  if (onlyPtBr.length > 0) {
    lines.push(`  keys in pt-BR.json but NOT in en.json (${onlyPtBr.length}):`);
    for (const k of onlyPtBr) lines.push(`    - ${k}`);
  }
  fail(lines.join('\n'));
}

function emitKeysDts(): void {
  const content = `/**
 * AUTOGENERATED by scripts/check-locales.ts — do not edit by hand.
 *
 * This file derives a \`TranslationKey\` string-literal union from \`en.json\`
 * and augments i18next's \`CustomTypeOptions\` so \`t(key)\` call sites get
 * autocomplete and compile-time checking against the source-of-truth catalog.
 *
 * Re-run \`npm run check:locales\` to regenerate after adding or removing keys.
 */

import 'i18next';
import type enCatalog from './en.json';

export type TranslationKey = keyof typeof enCatalog;

declare module 'i18next' {
  interface CustomTypeOptions {
    defaultNS: 'translation';
    returnNull: false;
    resources: {
      translation: typeof enCatalog;
    };
  }
}
`;
  try {
    writeFileSync(KEYS_DTS_PATH, content, 'utf8');
  } catch (err) {
    fail(`failed to write ${KEYS_DTS_PATH}: ${(err as Error).message}`);
  }
}

function main(): void {
  const { data: en } = readCatalog(EN_PATH);
  const { data: ptBr } = readCatalog(PTBR_PATH);

  validateValues(EN_PATH, en);
  validateValues(PTBR_PATH, ptBr);

  validateSorted(EN_PATH, en);
  validateSorted(PTBR_PATH, ptBr);

  validateParity(new Set(Object.keys(en)), new Set(Object.keys(ptBr)));

  emitKeysDts();

  process.stdout.write(
    `[check-locales] OK — ${Object.keys(en).length} keys, parity verified, keys.d.ts emitted.\n`,
  );
}

main();
